export const LIST_PACIENTS = 'LIST_PACIENTS';
export const REGISTER_PACIENT = 'REGISTER_PACIENT';
export const UPDATE_PACIENT = 'UPDATE_PACIENT';
export const DELETE_PACIENT = 'DELETE_PACIENT';
export const LIST_USERS = 'LIST_USERS';
export const REGISTER_USER = 'REGISTER_USERS';
export const UPDATE_USER = 'UPDATE_USERS';
export const DELETE_USER = 'DELETE_USERS';

